### ISSUE TITLE
[Bug]: Source generator emits invalid C# when method parameter uses @namespace escaped identifier (regression in 13.1.0)

### ISSUE THREAD

**Issue by zwikk** [reactiveui/refit#2247]
### Describe the bug 🐞

Since upgrading from Refit 13.0.0 to 13.1.0, the Refit source generator emits invalid C# code when an interface method contains a parameter whose name is an escaped identifier using the @ prefix (e.g. @namespace).
This scenario worked correctly in Refit 13.0.0 and earlier versions. Starting with 13.1.0, the generated source contains invalid code and compilation fails.
It appears that the source generator is not correctly handling escaped identifiers when generating code.

### Step to reproduce

1. Create a Refit interface similar to the following:
```C#
public interface ITestApi
{
  [Get("/test/{namespace}")]
  Task<string> GetAsync(string @namespace);
}
```
2. Install Refit 13.1.0 (or later).
3. Build the project.
4. Inspect the generated source and/or observe the compilation errors.

### Reproduction repository

https://github.com/reactiveui/refit

### Expected behavior

The source generator should correctly handle escaped identifiers and emit valid C# source code.
The above example should compile successfully, matching the behavior of Refit 13.0.0 and earlier versions.

### Refit Version

13.1.0

**Comment by TimothyMakkison** [comment]
Can replicate the issue, looks like it isn't handling reserved keywords properly. This should be fixed in the beta version of 14.0.0 (note that it is experimental)

<img width="1419" height="223" alt="Image" src="https://github.com/user-attachments/assets/9a0b233f-c44c-4570-9a05-c42d08d0d483" />

<img width="1405" height="194" alt="Image" src="https://github.com/user-attachments/assets/338a345a-d6e1-48cb-aa6e-f3252b6faec9" />

**Comment by glennawatson** [comment]
@zwikk this was fixed as part of the reflection-free source-generator rewrite in the 14.0.0 beta. I verified it against your exact repro - a `[Get("/test/{namespace}")]` route with a `string @namespace` parameter - plus escaped-keyword parameters in query, body, and header positions, and the generated code now compiles in every case.

Could you give the beta a try and confirm it resolves this for you?
https://www.nuget.org/packages/Refit/14.0.0-beta.1

Note the 14.0.0 line is still a beta (experimental) ahead of the stable release.

<blockquote><img src="https://api.nuget.org/v3-flatcontainer/refit/14.0.0-beta.1/icon" width="48" align="right"><div><strong><a href="https://nuget.org/packages/Refit/">Refit 14.0.0-beta.1</a></strong></div><div>Type-safe REST API clients for .NET, generated from annotated interfaces with build-time source generation, direct request construction, System.Text.Json defaults, and support for trimming and AOT.</div></blockquote>

**Comment by glennawatson** [comment]
I'm adding tests to make sure we don't regress in this scenario to the code base though.

**Comment by zwikk** [comment]
> Could you give the beta a try and confirm it resolves this for you? https://www.nuget.org/packages/Refit/14.0.0-beta.1
> 
> Note the 14.0.0 line is still a beta (experimental) ahead of the stable release.

Confirmed, 14.0.0 works fine.

<blockquote><img src="https://api.nuget.org/v3-flatcontainer/refit/14.0.0-beta.1/icon" width="48" align="right"><div><strong><a href="https://nuget.org/packages/Refit/">Refit 14.0.0-beta.1</a></strong></div><div>Type-safe REST API clients for .NET, generated from annotated interfaces with build-time source generation, direct request construction, System.Text.Json defaults, and support for trimming and AOT.</div></blockquote>

**Comment by glennawatson** [comment]
Thanks, closing, also found a regression in other cases though and fix this morning in #2248
